// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlb6awcJbQOBrrKP-dAjMzSaPIvWZ44mk',
    appId: '1:86873546841:web:89b63ac2fa74598787d148',
    messagingSenderId: '86873546841',
    projectId: 'attendanz-app',
    authDomain: 'attendanz-app.firebaseapp.com',
    storageBucket: 'attendanz-app.firebasestorage.app',
    measurementId: 'G-GG9JL4P760',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWGB7CQ3wU4ukGk__q9S7CjO2mDacugA',
    appId: '1:86873546841:android:4e07eeafc69ebf6a87d148',
    messagingSenderId: '86873546841',
    projectId: 'attendanz-app',
    storageBucket: 'attendanz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQz655uWc6Fpx4nGJci3a71nAqo5Cxw0',
    appId: '1:86873546841:ios:3976478ef018ad6a87d148',
    messagingSenderId: '86873546841',
    projectId: 'attendanz-app',
    storageBucket: 'attendanz-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQz655uWc6Fpx4nGJci3a71nAqo5Cxw0',
    appId: '1:86873546841:ios:3976478ef018ad6a87d148',
    messagingSenderId: '86873546841',
    projectId: 'attendanz-app',
    storageBucket: 'attendanz-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlb6awcJbQOBrrKP-dAjMzSaPIvWZ44mk',
    appId: '1:86873546841:web:413537d2cbb7a16187d148',
    messagingSenderId: '86873546841',
    projectId: 'attendanz-app',
    authDomain: 'attendanz-app.firebaseapp.com',
    storageBucket: 'attendanz-app.firebasestorage.app',
    measurementId: 'G-YYKNX1QVE6',
  );
}
